# Generated by Django 3.2 on 2021-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_qrcode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
