# Generated by Django 3.2 on 2021-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_qrcode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_invoice',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
