# Generated by Django 3.2 on 2021-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_order_qr_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
