# Generated by Django 3.2 on 2021-05-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
